### ISSUE TITLE
Visualizar Lista de Scores

### ISSUE THREAD

**Issue by alinecintracamargo** [desenvolvendo-me/lead-score#27]
**Nome:** Visualizar Lista de Scores

**Descrição:** Como desenvolvedora, eu quero criar a visualização de uma lista de scores de possíveis compradores de um roduto, para identificar os clientes mais promissores.

**Critério de Aceite:** O sistema deve exibir uma lista paginada de scores dos possíveis compradores de um produto.

**Valor para o Usuário:** Facilitar a identificação e priorização dos clientes mais promissores.

**Tarefas:**

- [x] #30 
- [x] #33

**Comment by marcodotcastro** [comment]
LEAD_SCORE_DADOS:
      dados_lead
      score
