### ISSUE TITLE
Épico 3 - Algoritmo de pontuação

### ISSUE THREAD

**Issue by Pjmaciel** [desenvolvendo-me/lead-score#3]
Objetivo: Implementar um sistema automatizado, que calcula a pontuação de leads com base em suas respostas a uma pesquisa, utilizando uma tabela de pesos previamente definida.

Principal Entrega: Um módulo que calcula e exibe a pontuação total de cada lead com base nos pesos atribuídos às suas respostas, facilitando a análise posterior pela equipe responsável.

Critérios de Aceitação:

- [x] #11  
- [x] #16

**Comment by marcodotcastro** [comment]
LEAD_JSON: 
{
      lead: {
            name: "Marco",
            email: "marcodotcastro@gmail.com",
            telefone: "18121212"
      }, respostas: {
            "Você já comprou algum curso de Programação?" => "Sim",
            "Você está em transição de carreira?" => "Sim",
      }
}



PESO_DADOS: 
      description: "Alunos Turma 21"
      situação: true
      tabela_peso_json: {
            "Você já comprou algum curso de Programação?": 
            { "Sim": 5, "Não": 1 },
            "Você está em transição de carreira?": 
            { "Sim": 4, "Não": 2 }
      }


LEAD_SCORE_DADOS:
      dados_lead
      score
